Intial commit on the sentence creator
KhalisFoundation/gurmukhi pull request #11
Opened 2023-06-27 04:38 UTC by lbk003

2023-08-24 00:42 UTC, MySmilingTurban requested changes
added suggestions for few minor changes
can add pylint and docstrings, if needed

2023-08-24 00:42 UTC, MySmilingTurban commented on sentencecreator/.gitignore
> +
can remove these comments

2023-08-24 00:42 UTC, MySmilingTurban commented on sentencecreator/sentencecreator.py
> +
remove empty line

2023-08-24 00:42 UTC, MySmilingTurban commented on sentencecreator/sentencecreator.py
> +    prompt += f"For each of these words, create {sentence_count} sentences using the word for a grade 3 student."
Line too long, should have max 100 characters

2023-08-24 00:42 UTC, MySmilingTurban commented on sentencecreator/sentencecreator.py
> +    prompt += f"Draft the response as a comma delimited list that can be saved as a csv file. Column 0 is the word, Column 1 through {sentence_count} are the {sentence_count} sentences generated for
Line too long, should have max 100 characters

2023-08-24 00:42 UTC, MySmilingTurban commented on sentencecreator/sentencecreator.py
> +    main()
nit: add new line

2023-08-27 02:30 UTC, lbk003 commented on sentencecreator/sentencecreator.py
> +
Done

2023-08-27 02:36 UTC, lbk003 commented on sentencecreator/sentencecreator.py
> +    prompt += f"Draft the response as a comma delimited list that can be saved as a csv file. Column 0 is the word, Column 1 through {sentence_count} are the {sentence_count} sentences generated for
done

2023-08-27 02:37 UTC, lbk003 commented on sentencecreator/sentencecreator.py
> +    main()
done

2023-08-27 02:41 UTC, lbk003 commented
> added suggestions for few minor changes can add pylint and docstrings, if needed

Will definitely do that when we bump up the quality from poc

2023-08-27 02:46 UTC, MySmilingTurban approved these changes
Looks good to me!

2023-08-27 15:00 UTC, merged