Latest
KhalisFoundation/gurmukhi pull request #12
Opened 2023-07-08 23:40 UTC by MySmilingTurban

This PR includes the following changes:
- Converting JavaScript code to Typescript
- Implementation of CRUD functionality for words and wordlists using queries to Cloud Firestore database
- Implementation of Role management system to manage creator, reviewer and admin 
- Authentication implemented with Firebase auth

2023-07-15 01:14 UTC, lbk003 requested changes
Please add unit tests, move roles  and permissions to a separate library, change the way wordlists contain words.

2023-07-15 01:14 UTC, lbk003 commented on shabadkosh/src/index.css
> +  /* add sick abstract neumorphism on white bg design background and shadows */
?

2023-07-15 01:14 UTC, lbk003 commented on shabadkosh/src/index.css
> +}
nit: new line

2023-07-15 01:14 UTC, lbk003 commented on shabadkosh/src/types/user.ts
> +    role?: string,
like we discussed, better to use the firebase library

2023-07-18 10:00 UTC, MySmilingTurban commented on shabadkosh/src/types/user.ts
> +    role?: string,
got resolved in a discussion

2023-07-18 10:00 UTC, MySmilingTurban commented on shabadkosh/src/components/constants/index.ts
> +// old status tags
removed

2023-07-18 10:01 UTC, MySmilingTurban commented on shabadkosh/src/components/Search.tsx
> +        // console.log("words", words);
will create a code cleanup task for this

2023-07-18 10:01 UTC, MySmilingTurban commented on shabadkosh/src/App.tsx
> +          /> */}
will create a code cleanup task for this

2023-07-26 12:03 UTC, theamanjs commented
Veerji, there are some ESlint and build issues shown on the merge checklist check. Let's fix that; meanwhile, I'm reviewing the rest of the code.

https://github.com/KhalisFoundation/gurmukhi/actions/runs/5657288589/job/15326011874?pr=12
https://github.com/KhalisFoundation/gurmukhi/pull/12/checks?check_run_id=15326017147

2023-07-26 16:17 UTC, theamanjs requested changes
1. The images are toooo big.
2. Component structure could be improved. Instead of having all the files in one folder, we should create a separate folder for related files. Like About.js and About.jsx should be in about folder.
3. Why we are not using SCSS?

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/util/controller.ts
> +import { DocumentReference, Timestamp, addDoc, arrayRemove, arrayUnion, collection, deleteDoc, doc, documentId, getDoc, getDocs, query, updateDoc, where, writeBatch } from 'firebase/firestore';
every import variables would be going to new line to reduce the line width. 

We should add airbnb eslint to this project to enforce all the best practices rules

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/util/controller.ts
> +    return words;
In some files the indentation is of two white spaces and in other it's four white spaces. There must be a standard and enforced using a linter (2 spaces recommended)

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/util/users.ts
> +    // const userSnap = await getDoc(userRef);
Seems like unwanted comment

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/util/users.ts
> +export const checkUser = async (uid: string, email: string) => {
Checkuser function should be separated into a file. I'm not commenting about this in the rest of this PR but this fix should be done on all the places where we are using this function

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/util/users.ts
> +}
add an empty line in the end

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/index.css
> +  margin-right: 10%;
margins in percent seems off. I guess there must be a better way to solve this issue. We may end up seeing some weird UI issues because of this

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/firebase.ts
> +  measurementId: process.env.REACT_APP_measurementId,
Create one readme file and mention all the variables in that file. So that installation process can become more accessible.

2023-07-26 16:17 UTC, theamanjs commented on shabadkosh/src/components/words/WordDetail.tsx
> +                  <NavLink style={{width: '150px', border: '1px solid #000', borderRadius: 20, textAlign: 'center', margin: 5}} href={`/words/${antonym.id}`} key={antonym.id}>{antonym.word}</NavLink>
breakdown the line to reduce the characters in one line. Should not exceed 100 chars. Add airbnb eslint style guide

2023-07-30 23:10 UTC, MySmilingTurban commented on shabadkosh/src/components/Search.tsx
> +            <td>{word.created_by}</td>
Veerji, the data stored in firestore document is ordered by key, and we need to show the word data in a specific way, say word followed by translation and so on.

2023-07-30 23:12 UTC, MySmilingTurban commented on shabadkosh/src/components/UserAuthContext.tsx
> +        }
Veerji, could you please elaborate a bit.

2023-07-31 14:35 UTC, MySmilingTurban commented
> 1. The images are toooo big.
> 2. Component structure could be improved. Instead of having all the files in one folder, we should create a separate folder for related files. Like About.js and About.jsx should be in about folder.
> 3. Why we are not using SCSS?

1. The images' size is used as 1920 x 1080, in the internal tool they are displayed as small whereas in the actual app implementation it needs to go full screen images at times.
2. Thanks, restructured accordingly

2023-08-03 12:31 UTC, theamanjs requested changes

2023-08-03 12:31 UTC, theamanjs commented on shabadkosh/src/components/home/Home.tsx
> +function Home() {
I prefer es6 function. Why did we downgrade?

2023-08-03 12:31 UTC, theamanjs commented on shabadkosh/src/components/search/Search.tsx
> +            </tr>
Strongly recommended to add loop

2023-08-03 12:31 UTC, theamanjs commented on shabadkosh/src/components/util/utils.ts
> +  if (!timestamp) return 'Invalid time';
1. String not from i18n
2. if should follow proper syntax with braces
```js
if (!timestap) {
  ...
}
```

2023-08-03 12:31 UTC, theamanjs commented on shabadkosh/src/components/wordlists/AddWordlist.tsx
> +  if (isLoading) return <div>{t('LOADING')}</div>;
proper if syntax with braces

2023-08-04 07:38 UTC, MySmilingTurban commented on shabadkosh/src/components/search/Search.tsx
> +            </tr>
Veerji, the data stored in firestore document is ordered by key, and we need to show the word data in a specific way, say, word followed by translation and so on. That is the main reason why we're going with this approach.

2023-08-04 08:33 UTC, theamanjs commented on shabadkosh/src/components/search/Search.tsx
> +            </tr>
Okay veerji

2023-08-04 08:35 UTC, theamanjs requested changes

2023-08-04 08:35 UTC, theamanjs commented on shabadkosh/src/components/auth/Logout.tsx
> +function Logout() {
veerji I think there's some miscommunication. I asked that we should prefer the latest es6 const functions. 

Also, not only for this file for all our files. Code should be in latest coding standards

2023-08-04 22:30 UTC, MySmilingTurban commented on shabadkosh/src/components/auth/Logout.tsx
> +function Logout() {
Apologies for the confusion veerji
Thanks for clarifying ji

2023-08-05 13:07 UTC, theamanjs approved these changes

2023-08-13 23:10 UTC, lbk003 approved these changes
Left some comments. Would be nice if you could fix and merge

2023-08-13 23:30 UTC, MySmilingTurban commented on shabadkosh/src/components/constants/status.ts
> +  FEEDBACK_ENGLISH: 'feedback-english',
review is the stage where the word goes to be checked by reviewer > decides whether it is good to goto prod(active) or needs any changes(feedback)
feedback is the stage when reviewer finds some bug/missing data which needs to be fixed by creator

for detailed description, refer to [this](https://docs.google.com/document/d/1ra0Nri8t45-W4YAmUpt3MDClktwg6C_l2X5Ymc_K7ZU/edit?usp=sharing)

2023-08-14 00:04 UTC, MySmilingTurban commented on shabadkosh/src/assets/singh.png
Agreed, we need kaur.png as well
For now, I can remove both from here as it is not being used in internal tool but will be used in main app

2023-08-14 02:45 UTC, merged