Questions form fix
KhalisFoundation/gurmukhi pull request #29
Opened 2023-08-25 04:38 UTC by MySmilingTurban

Added functionality to create new word whenever a new word option is added inside a question.
Also, adds a restriction that questions with sentences as its options shall be of type meaning.

2023-08-25 16:34 UTC, theamanjs requested changes

2023-08-25 16:34 UTC, theamanjs commented on shabadkosh/src/components/words/AddWord.tsx
> +      alert('Only question type - meaning can have sentences as options!');
strings should come from i18n

2023-08-25 16:34 UTC, theamanjs commented on shabadkosh/src/components/words/AddWord.tsx
> +            formData.status = lStatus ?? STATUS.CREATING_ENGLISH;
rename the lStatus to a better name which is obvious

2023-08-25 16:34 UTC, theamanjs commented on shabadkosh/src/components/words/EditWord.tsx
> +    const { lSentences, lQuestions, ...form } = formData;
What are lSentence and lQuestions? Please use elaborative names.

2023-08-25 16:34 UTC, theamanjs commented on shabadkosh/src/components/words/EditWord.tsx
> +                if (word.status === STATUS.REVIEW_ENGLISH) {
This logic is somewhat similar in addword file. Make a common function that can serve for both the places.

2023-08-26 07:40 UTC, MySmilingTurban commented on shabadkosh/src/components/words/EditWord.tsx
> +    const { lSentences, lQuestions, ...form } = formData;
Veerji, those are local scope variables for sentences and questions, I have now changed them to sentences, questions.
We are using the same variable names for managing their state with useState, that's why added "l" in the beginning
Lmk, what would be a better solution

2023-08-27 15:03 UTC, lbk003 reviewed
lgtm

2023-09-05 09:33 UTC, Gauravjeetsingh requested changes

2023-09-25 16:12 UTC, Gauravjeetsingh requested changes

2023-09-30 13:43 UTC, MySmilingTurban commented on shabadkosh/src/components/util/utils.ts
>    return 0;
updated_at has Firebase Timestamp datatype which looks like the following:

```
export interface TimestampType {
  seconds: number,
  nanoseconds: number,
}
```

2023-10-19 22:18 UTC, MySmilingTurban commented
@Gauravjeetsingh Veerji

2023-12-18 21:18 UTC, amitojsingh approved these changes

2023-12-18 21:19 UTC, amitojsingh commented
Looks good to me. Good job veer ji.

2023-12-18 23:25 UTC, merged